### ISSUE TITLE
Getting "Error: error:0308010C:digital envelope routines::unsupported" on yarn start

### ISSUE THREAD

**Issue by bruteforks** [software-mansion-labs/reanimated-2-playground#74]
Wondering if anyone can help out

`Failed to construct transformer:  Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at stableHash (/home/data2/code/opensource/reanimated-2-playground/node_modules/metro-cache/src/stableHash.js:19:8)
    at Object.getCacheKey (/home/data2/code/opensource/reanimated-2-playground/node_modules/metro-transform-worker/src/index.js:593:7)
    at getTransformCacheKey (/home/data2/code/opensource/reanimated-2-playground/node_modules/metro/src/DeltaBundler/getTransformCacheKey.js:24:19)
    at new Transformer (/home/data2/code/opensource/reanimated-2-playground/node_modules/metro/src/DeltaBundler/Transformer.js:48:9)
    at /home/data2/code/opensource/reanimated-2-playground/node_modules/metro/src/Bundler.js:22:29
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'`

[potentially related stackoverflow answer](https://stackoverflow.com/a/69699772)

**Comment by kacperkapusciak** [comment]
Closing as outdated issue

We've updated the repo to use the newest React Native & React Native Reanimated versions
